from typing import Protocol


class IWorkflowRepository(Protocol):
    def save_workspace(self, documents: list[dict], assets: dict, folders: list | None = None, active_id: str | None = None) -> None: ...
    def load(self, workflow_id: str) -> dict: ...
    def workspace(self) -> dict: ...
